### ISSUE TITLE
Extending the default model binder

### ISSUE THREAD

**Issue by janhartmann** [djhaley/InputScrubbingModelBinder#1]
Hi,

I am wondering if you have experience with extending the default model binder, to bind a property from an interface - using the request, and not the body? 

I've used some parts of your example, with no luck - maybe, if you have the time, please take a look at this question I've posted on the MVC repository: https://github.com/aspnet/Mvc/issues/5238

**Comment by djhaley** [comment]
For the fun of it I added an example using your model under the Issue1 branch.  It just sets UserId to Guid.NewGuid(), but certainly you could use the user id you want.

**Comment by janhartmann** [comment]
Thanks for your time, @djhaley - for some reason the `context.Metadata.ContainerType` is null - so the binder is not hit?

You think this is because my `IUserAware` lives in another assembly (which is by the way already references by the MVC project)

**Comment by janhartmann** [comment]
Hold on! It appears I had the `[FromBody]` attribute on the `AddCustomer` command in my action. If this is removed, your code is working brilliantly! :-)

Thanks a lot!

**Comment by janhartmann** [comment]
Okay, been investigating this a bit more - your example is not valid if the other properties should be bound from the body.

Lets say `name` and `age` is bound from the body and the `UserId` is bound from the request header. 

The model binder is is guarded against which types to bind for, using the ` if (typeof(IUserAware).IsAssignableFrom(context.Metadata.ContainerType) && context.Metadata.ModelType == typeof(Guid))`

When the model binder then kicks in and sets the model value with ` bindingContext.Result = ModelBindingResult.Success(Guid.NewGuid());` the whole model is actually overwritten and only the `UserId` is set. 

The other properties is null when finally hitting the action.

If I set the action arguments to be `public IActionResult Index([FromBody]AddCustomer entity)` the model binder is never used, and all other properties except `UserId` is set.

**Comment by djhaley** [comment]
If you include the [FromBody] you are telling the framework to specifically use the FormCollectionModelBinderProvider.  Without that attribute each property is sent through the list of providers until one asserts that it will handle the property by returning a model binder.

If you are passing just the UserId property to the model binder, then it should only affect that property and the rest of the model should be handled by other model binders.

The sample code in the Issue1 branch works for me.  If I enter Dan and 42 for name and age, then press Test It, I get back Dan, 42, and a new Guid.  To test using a value from HttpContext, in /Account I set a value for userId on HttpContext.Session.  Then in the UserAwareModelBinder I used that instead of Guid.NewGuid(), and I got back the session value after clicking Test It.

Can you post your code?

**Comment by janhartmann** [comment]
If I use the UI of yours, it works. But my use case is an API request - using your example without any modifications with this request, only the UserId is bound:

```
POST /AddCustomer HTTP/1.1
Host: localhost:50308
Content-Type: application/json
Cache-Control: no-cache
{
	"name": "Test",
	"age": 20
}
```
![udklip](https://cloud.githubusercontent.com/assets/1107383/18418546/e1437364-7848-11e6-92ba-2d3661e335c9.PNG)

Again, thank so much for your time.

**Comment by djhaley** [comment]
No problem - this is educational and kind of fun.  :)

Looks like I misspoke earlier - there is a BodyModelBinderProvider that handles [FromBody].  If you have to send in  your API requests as application/json then I *believe* you could create a BodyModelBinder by emulating how they create the BodyModelBinderProvider in your provider, but I didn't get it to work.  This provider is more complex as it has a couple of parameters and I'm not positive on what actually gets sent in.  I got the provider set up, but the call to the binder didn't bind anything.  If you wanted to explore this avenue the next step would be to grab the MVC source and debug through to see how it is handled.  

Is it possible to send your post request in with Content-Type = application/x-www-form-urlencoded and the body as name=Test&age=20?  That works with the current setup.

**Comment by janhartmann** [comment]
Yes, `x-www-form-urlencoded` works - but I need the request with a JSON body. 

Oh, well - guess I have to try implement my own `BodyModelBinder/BodyModelBinderProvider` in order to get it working. :-)

**Comment by janhartmann** [comment]
I've just talked with a few others about this, and we have come to the conclusion that this scenario is not meant for the model-binder. 

> The source of my problem is the fact that my command contains contextual information.

The way you are using the model binder for the scrubbing, is of course perfectly fine! :-) 

Thanks a lot for your time!
